version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment: 
      ConnectionStrings__APIContext: "Server=localhost;Database=BookData;User Id=sa;Password=Mssql!Server02;"
    ports:
      - "5000:5000"
    depends_on: 
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment: 
      SA_PASSWORD: "Mssql!Server02"
      ACCEPT_EULA: "Y"